- name: install mariadb
  yum:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: latest

- name: start mariadb
  service:
    name: mariadb
    enabled: true
    state: started

- name: mysql_root_password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: root
    check_implicit_admin: true
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL,GRANT"
    state: present
    host: "{{ http_ip }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: ensure mariadb binds to internal interface
  template: >-
    src=etc/my.cnf.d/mariadb-server.cnf
    dest=/etc/my.cnf.d/mariadb-server.cnf
    owner=root
    group=root
    mode=644
  notify:
      restart mariadb

- name: Configure Firewall
  firewalld: zone=public service=mysql permanent=yes state=enabled

- name: Reload Firewall
  systemd: name=firewalld state=reloaded
