# Install Remi Repository
# - name: Import remi GPG key
#   rpm_key:
#     key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
#     state: present

- name: Import remi GPG key 2018
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi2018
    state: present

- name: Install remi repo
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    state: present

- name: Enable PHP Remi Repository
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y

# Install PHP (and extensions)
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

# Need to disable SELinux for php to use mysql alternatively we could just allow httpd to use it 
# https://stackoverflow.com/questions/57270169/php-mysqli-permission-denied-but-working-from-mysql-cli
- name: Disable SELinux Permanently (Reboot Required)
  selinux: state=disabled

- name: Disable SELinux Without Reboot
  command: /sbin/setenforce 0