#PHP Settings
php_modules: [ 'php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'php-mysql' ]
 
#MySQL Settings
mysql_root_password: "your-root-password"
mysql_db_host: "192.168.50.32"
mysql_db: "wpdb"
mysql_user: "wpuser"
mysql_password: "password"
 
#HTTP Settings
http_host: "wp.example.com"
http_conf: "wp.example.com.conf"
http_port: "80"